const MIN_TABLET_WIDTH = 600;
const MIN_PHONE_WIDTH = 321;
const MIN_ANDROID_HEIGHT_PHONE = 427;
const MAX_ANDROID_PHONE_WIDTH = 412;

export {
  MIN_TABLET_WIDTH,
  MIN_PHONE_WIDTH,
  MIN_ANDROID_HEIGHT_PHONE,
  MAX_ANDROID_PHONE_WIDTH
};
